name: ttorok
description: "글또 개발자 커뮤니티에서 또봇(글제출 및 기록 저장 로봇)이 저장한 사람들의 기록들을 한눈에 보여주는 웹 페이지 '또록'입니다."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.9
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/
  fonts:
    - family: LINESeedKR-Bd
      fonts:
        - asset: assets/fonts/LINESeedKR-Bd.otf
    - family: LINESeedKR-Rg
      fonts:
        - asset: assets/fonts/LINESeedKR-Rg.otf
    - family: LINESeedKR-Th
      fonts:
        - asset: assets/fonts/LINESeedKR-Th.otf